# Generated by Django 5.2.7 on 2025-11-04 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='follower',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='following',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='followers',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор'),
        ),
    ]
